#ifndef ENUM_ACHIEVEMENT_FLAGS_H
#define ENUM_ACHIEVEMENT_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (AchievementFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue achievement_flags_values[] = {
    { 0x00000001, "Counter"           },
    { 0x00000002, "Hidden"            },
    { 0x00000004, "Store Max Value"   },
    { 0x00000008, "Summ"              },
    { 0x00000010, "Max Used"          },
    { 0x00000020, "Req Count"         },
    { 0x00000040, "Average"           },
    { 0x00000080, "Bar"               },
    { 0x00000100, "Realm First Reach" },
    { 0x00000200, "Realm First Kill"  },
};

static const DbcEnum achievement_flags_enum = {
    "AchievementFlags", achievement_flags_values,
    sizeof(achievement_flags_values) / sizeof(achievement_flags_values[0]) };

#endif
