#ifndef ENUM_SPELL_ATTR1_H
#define ENUM_SPELL_ATTR1_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr1 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr1_values[] = {
    { 0x00000001, "Dismiss Pet on cast"                                      },
    { 0x00000002, "Drain all power"                                          },
    { 0x00000004, "Channeled (type 1)"                                       },
    { 0x00000008, "Ignore redirection effects"                               },
    { 0x00000010, "Unknown attribute 4"                                      },
    { 0x00000020, "Does not break stealth"                                   },
    { 0x00000040, "Channeled (type 2)"                                       },
    { 0x00000080, "Ignore reflection effects"                                },
    { 0x00000100, "Target cannot be in combat"                               },
    { 0x00000200, "Starts auto-attack (client only)"                         },
    { 0x00000400, "Does not generate threat"                                 },
    { 0x00000800, "Aura will not refresh its duration when recast"           },
    { 0x00001000, "Pickpocket (client only)"                                 },
    { 0x00002000, "Farsight aura (client only)"                              },
    { 0x00004000, "Track target while channeling"                            },
    { 0x00008000, "Immunity cancels preapplied auras"                        },
    { 0x00010000, "Unaffected by school immunities"                          },
    { 0x00020000, "Cannot be autocast by pet"                                },
    { 0x00040000, "NYI, auras apply UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT" },
    { 0x00080000, "Cannot be self-cast"                                      },
    { 0x00100000, "Requires combo points (type 1)"                           },
    { 0x00200000, "Unknown attribute 21"                                     },
    { 0x00400000, "Requires combo points (type 2)"                           },
    { 0x00800000, "Unknwon attribute 23"                                     },
    { 0x01000000, "Fishing (client only)"                                    },
    { 0x02000000, "Unknown attribute 25"                                     },
    { 0x04000000, "Require All Targets"                                      },
    { 0x08000000, "Unknown attribute 27"                                     },
    { 0x10000000, "Hide in aura bar (client only)"                           },
    { 0x20000000, "Show spell name during channel (client only)"             },
    { 0x40000000, "Enable at dodge"                                          },
    { 0x80000000, "Unknown attribute 31"                                     },
};

static const DbcEnum spell_attr1_enum = {
    "SpellAttr1", spell_attr1_values,
    sizeof(spell_attr1_values) / sizeof(spell_attr1_values[0]) };

#endif
