#ifndef ENUM_SPELL_ATTR4_H
#define ENUM_SPELL_ATTR4_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr4 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr4_values[] = {
    { 0x00000001, "Cannot be resisted"                                      },
    { 0x00000002, "Only proc on self-cast"                                  },
    { 0x00000004, "Buff expires while offline"                              },
    { 0x00000008, "Unknown attribute 3"                                     },
    { 0x00000010, "Treat as delayed spell"                                  },
    { 0x00000020, "Unknown attribute 5"                                     },
    { 0x00000040, "Aura cannot be stolen"                                   },
    { 0x00000080, "Can be cast while casting"                               },
    { 0x00000100, "Deals fixed damage"                                      },
    { 0x00000200, "Spell is initially disabled (client only)"               },
    { 0x00000400, "Attack speed modifies cost"                              },
    { 0x00000800, "Unknown attribute 11"                                    },
    { 0x00001000, "Unknown attribute 12"                                    },
    { 0x00002000, "Unknown attribute 13"                                    },
    { 0x00004000, "Damage does not break auras"                             },
    { 0x00008000, "Unknown attribute 15"                                    },
    { 0x00010000, "Not usable in arena"                                     },
    { 0x00020000, "Usable in arena"                                         },
    { 0x00040000, "Chain area targets"                                      },
    { 0x00080000, "Unknown attribute 19"                                    },
    { 0x00100000, "Allow self-cast to override stronger aura (client only)" },
    { 0x00200000, "Keep when entering arena"                                },
    { 0x00400000, "Unknown attribute 22"                                    },
    { 0x00800000, "Cannot trigger item spells"                              },
    { 0x01000000, "Unknown attribute 24"                                    },
    { 0x02000000, "Pet Scaling aura"                                        },
    { 0x04000000, "Only in Outland/Northrend"                               },
    { 0x08000000, "Force Display Castbar"                                   },
    { 0x10000000, "Unknown attribute 28"                                    },
    { 0x20000000, "Unknown attribute 29"                                    },
    { 0x40000000, "Unknown attribute 30"                                    },
    { 0x80000000, "Unknown attribute 31"                                    },
};

static const DbcEnum spell_attr4_enum = {
    "SpellAttr4", spell_attr4_values,
    sizeof(spell_attr4_values) / sizeof(spell_attr4_values[0]) };

#endif
