#ifndef ENUM_CREATURE_ELITE_TYPE_H
#define ENUM_CREATURE_ELITE_TYPE_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (CreatureEliteType in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue creature_elite_type_values[] = {
    {          0, "Normal"    },
    {          1, "Elite"     },
    {          2, "Rareelite" },
    {          3, "Worldboss" },
    {          4, "Rare"      },
    {          5, "Trivial"   },
};

static const DbcEnum creature_elite_type_enum = {
    "CreatureEliteType", creature_elite_type_values,
    sizeof(creature_elite_type_values) / sizeof(creature_elite_type_values[0]) };

#endif
