#ifndef ENUM_SPELL_ATTR0_H
#define ENUM_SPELL_ATTR0_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr0 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr0_values[] = {
    { 0x00000001, "Unknown attribute 0"                                 },
    { 0x00000002, "Treat as ranged attack"                              },
    { 0x00000004, "On next melee (type 1)"                              },
    { 0x00000008, "Replenishment (client only)"                         },
    { 0x00000010, "Treat as ability"                                    },
    { 0x00000020, "Trade skill recipe"                                  },
    { 0x00000040, "Passive spell"                                       },
    { 0x00000080, "Hidden in UI (client only)"                          },
    { 0x00000100, "Hidden in combat log (client only)"                  },
    { 0x00000200, "Auto-target mainhand item (client only)"             },
    { 0x00000400, "On next melee (type 2)"                              },
    { 0x00000800, "Unknown attribute 11"                                },
    { 0x00001000, "Only usable during daytime (unused)"                 },
    { 0x00002000, "Only usable during nighttime (unused)"               },
    { 0x00004000, "Only usable indoors"                                 },
    { 0x00008000, "Only usable outdoors"                                },
    { 0x00010000, "Not usable while shapeshifted"                       },
    { 0x00020000, "Only usable in stealth"                              },
    { 0x00040000, "Don't shealthe weapons (client only)"                },
    { 0x00080000, "Scale with caster level"                             },
    { 0x00100000, "Stop attacking after cast"                           },
    { 0x00200000, "Prevent physical avoidance"                          },
    { 0x00400000, "Automatically face target during cast (client only)" },
    { 0x00800000, "Can be cast while dead"                              },
    { 0x01000000, "Can be cast while mounted"                           },
    { 0x02000000, "Cooldown starts on expiry"                           },
    { 0x04000000, "Is negative spell"                                   },
    { 0x08000000, "Can be cast while sitting"                           },
    { 0x10000000, "Cannot be used in combat"                            },
    { 0x20000000, "Pierce invulnerability"                              },
    { 0x40000000, "Periodic resistance checks"                          },
    { 0x80000000, "Aura cannot be cancelled"                            },
};

static const DbcEnum spell_attr0_enum = {
    "SpellAttr0", spell_attr0_values,
    sizeof(spell_attr0_values) / sizeof(spell_attr0_values[0]) };

#endif
