#ifndef ENUM_VEHICLE_SEAT_FLAGS_H
#define ENUM_VEHICLE_SEAT_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (VehicleSeatFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue vehicle_seat_flags_values[] = {
    { 0x00000001, "Has Lower Anim For Enter"                         },
    { 0x00000002, "Has Lower Anim For Ride"                          },
    { 0x00000004, "Unk3"                                             },
    { 0x00000008, "Should Use Veh Seat Exit Anim On Voluntary Exit"  },
    { 0x00000010, "Unk5"                                             },
    { 0x00000020, "Unk6"                                             },
    { 0x00000040, "Unk7"                                             },
    { 0x00000080, "Unk8"                                             },
    { 0x00000100, "Unk9"                                             },
    { 0x00000200, "Hide Passenger"                                   },
    { 0x00000400, "Allow Turning"                                    },
    { 0x00000800, "Can Control"                                      },
    { 0x00001000, "Can Cast Mount Spell"                             },
    { 0x00002000, "Uncontrolled"                                     },
    { 0x00004000, "Can Attack"                                       },
    { 0x00008000, "Should Use Veh Seat Exit Anim On Forced Exit"     },
    { 0x00010000, "Unk17"                                            },
    { 0x00020000, "Unk18"                                            },
    { 0x00040000, "Has Veh Exit Anim Voluntary Exit"                 },
    { 0x00080000, "Has Veh Exit Anim Forced Exit"                    },
    { 0x00100000, "Passenger Not Selectable"                         },
    { 0x00200000, "Unk22"                                            },
    { 0x00400000, "Rec Has Vehicle Enter Anim"                       },
    { 0x00800000, "Is Using Vehicle Controls"                        },
    { 0x01000000, "Enable Vehicle Zoom"                              },
    { 0x02000000, "Can Enter Or Exit"                                },
    { 0x04000000, "Can Switch"                                       },
    { 0x08000000, "Has Start Wariting For Veh Transition Anim Enter" },
    { 0x10000000, "Has Start Wariting For Veh Transition Anim Exit"  },
    { 0x20000000, "Can Cast"                                         },
    { 0x40000000, "Unk2"                                             },
    { 0x80000000, "Allows Interaction"                               },
};

static const DbcEnum vehicle_seat_flags_enum = {
    "VehicleSeatFlags", vehicle_seat_flags_values,
    sizeof(vehicle_seat_flags_values) / sizeof(vehicle_seat_flags_values[0]) };

#endif
