#ifndef ENUM_DUNGEON_STATUS_FLAG_H
#define ENUM_DUNGEON_STATUS_FLAG_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (DungeonStatusFlag in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue dungeon_status_flag_values[] = {
    {          1, "Dungeon Statusflag Normal"    },
    {          2, "Dungeon Statusflag Heroic"    },
    {          4, "Raid Statusflag 10man Heroic" },
    {          8, "Raid Statusflag 25man Heroic" },
};

static const DbcEnum dungeon_status_flag_enum = {
    "DungeonStatusFlag", dungeon_status_flag_values,
    sizeof(dungeon_status_flag_values) / sizeof(dungeon_status_flag_values[0]) };

#endif
