#ifndef ENUM_LANGUAGE_H
#define ENUM_LANGUAGE_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (Language in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue language_values[] = {
    {          0, "Universal"      },
    {          1, "Orcish"         },
    {          2, "Darnassian"     },
    {          3, "Taurahe"        },
    {          6, "Dwarvish"       },
    {          7, "Common"         },
    {          8, "Demonic"        },
    {          9, "Titan"          },
    {         10, "Thalassian"     },
    {         11, "Draconic"       },
    {         12, "Kalimag"        },
    {         13, "Gnomish"        },
    {         14, "Troll"          },
    {         33, "Gutterspeak"    },
    {         35, "Draenei"        },
    {         36, "Zombie"         },
    {         37, "Gnomish Binary" },
    {         38, "Goblin Binary"  },
    { 4294967295, "Addon"          },
};

static const DbcEnum language_enum = {
    "Language", language_values,
    sizeof(language_values) / sizeof(language_values[0]) };

#endif
