#ifndef ENUM_SPELL_ATTR7_H
#define ENUM_SPELL_ATTR7_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr7 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr7_values[] = {
    { 0x00000001, "Unknown attribute 0"                                },
    { 0x00000002, "Ignore duration modifiers"                          },
    { 0x00000004, "Disable Aura While Dead"                            },
    { 0x00000008, "Is cheat spell"                                     },
    { 0x00000010, "Unknown attribute 4"                                },
    { 0x00000020, "Summons player-owned totem"                         },
    { 0x00000040, "Damage dealt by this does not cause spell pushback" },
    { 0x00000080, "Unknown attribute 7"                                },
    { 0x00000100, "Horde only"                                         },
    { 0x00000200, "Alliance only"                                      },
    { 0x00000400, "Dispel/Spellsteal remove individual charges"        },
    { 0x00000800, "Only interrupt non-player casting"                  },
    { 0x00001000, "Unknown attribute 12"                               },
    { 0x00002000, "Unknown attribute 13"                               },
    { 0x00004000, "Unknown attribute 14"                               },
    { 0x00008000, "Unknown attribute 15"                               },
    { 0x00010000, "Can restore secondary power"                        },
    { 0x00020000, "Unknown attribute 17"                               },
    { 0x00040000, "Has charge effect"                                  },
    { 0x00080000, "Is zone teleport"                                   },
    { 0x00100000, "Unknown attribute 20"                               },
    { 0x00200000, "Unknown attribute 21"                               },
    { 0x00400000, "Ignore cold weather flying restriction"             },
    { 0x00800000, "Spell cannot be dodged"                             },
    { 0x01000000, "Spell cannot be parried"                            },
    { 0x02000000, "Spell cannot be missed"                             },
    { 0x04000000, "Unknown attribute 26"                               },
    { 0x08000000, "Bypasses the prevent resurrection aura"             },
    { 0x10000000, "Consolidate in raid buff frame (client only)"       },
    { 0x20000000, "Unknown attribute 29"                               },
    { 0x40000000, "Unknown attribute 30"                               },
    { 0x80000000, "Client indicator (client only)"                     },
};

static const DbcEnum spell_attr7_enum = {
    "SpellAttr7", spell_attr7_values,
    sizeof(spell_attr7_values) / sizeof(spell_attr7_values[0]) };

#endif
