#ifndef ENUM_RACE_H
#define ENUM_RACE_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (Races in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue race_values[] = {
    {          0, "None"          },
    {          1, "Human"         },
    {          2, "Orc"           },
    {          3, "Dwarf"         },
    {          4, "Nightelf"      },
    {          5, "Undead Player" },
    {          6, "Tauren"        },
    {          7, "Gnome"         },
    {          8, "Troll"         },
    {         10, "Bloodelf"      },
    {         11, "Draenei"       },
};

static const DbcEnum race_enum = {
    "Race", race_values,
    sizeof(race_values) / sizeof(race_values[0]) };

#endif
