#ifndef ENUM_CLASS_H
#define ENUM_CLASS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (Classes in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue class_values[] = {
    {          0, "None"         },
    {          1, "Warrior"      },
    {          2, "Paladin"      },
    {          3, "Hunter"       },
    {          4, "Rogue"        },
    {          5, "Priest"       },
    {          6, "Death Knight" },
    {          7, "Shaman"       },
    {          8, "Mage"         },
    {          9, "Warlock"      },
    {         11, "Druid"        },
};

static const DbcEnum class_enum = {
    "Class", class_values,
    sizeof(class_values) / sizeof(class_values[0]) };

#endif
