#ifndef ENUM_SPELL_ATTR2_H
#define ENUM_SPELL_ATTR2_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr2 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr2_values[] = {
    { 0x00000001, "Can target dead players or corpses"   },
    { 0x00000002, "Unknown attribute 1"                  },
    { 0x00000004, "Ignore Line of Sight"                 },
    { 0x00000008, "Allow Low Level Buff"                 },
    { 0x00000010, "Show in stance bar (client only)"     },
    { 0x00000020, "Ranged auto-attack spell"             },
    { 0x00000040, "Cannot target others' tapped units"   },
    { 0x00000080, "Unknown attribute 7"                  },
    { 0x00000100, "Unknown attribute 8"                  },
    { 0x00000200, "Unknown attribute 9"                  },
    { 0x00000400, "Unknown attribute 10"                 },
    { 0x00000800, "Health Funnel"                        },
    { 0x00001000, "Unknown attribute 12"                 },
    { 0x00002000, "Enchant persists when entering arena" },
    { 0x00004000, "Unknown attribute 14"                 },
    { 0x00008000, "Unknown attribute 15"                 },
    { 0x00010000, "Tame Beast"                           },
    { 0x00020000, "Don't reset swing timer"              },
    { 0x00040000, "Requires dead pet"                    },
    { 0x00080000, "Also allow outside shapeshift"        },
    { 0x00100000, "Unknown attribute 20"                 },
    { 0x00200000, "Fail on all targets immune"           },
    { 0x00400000, "Unknown attribute 22"                 },
    { 0x00800000, "Arcane Concentration"                 },
    { 0x01000000, "Unknown attribute 24"                 },
    { 0x02000000, "Unknown attribute 25"                 },
    { 0x04000000, "Pierce aura application immunities"   },
    { 0x08000000, "Unknown attribute 27"                 },
    { 0x10000000, "Unknown attribute 28"                 },
    { 0x20000000, "Cannot critically strike"             },
    { 0x40000000, "Active Threat"                        },
    { 0x80000000, "Food buff (client only)"              },
};

static const DbcEnum spell_attr2_enum = {
    "SpellAttr2", spell_attr2_values,
    sizeof(spell_attr2_values) / sizeof(spell_attr2_values[0]) };

#endif
