#ifndef ENUM_SKILL_CATEGORY_H
#define ENUM_SKILL_CATEGORY_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SkillCategory in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue skill_category_values[] = {
    {          5, "Attributes" },
    {          6, "Weapon"     },
    {          7, "Class"      },
    {          8, "Armor"      },
    {          9, "Secondary"  },
    {         10, "Languages"  },
    {         11, "Profession" },
    {         12, "Generic"    },
};

static const DbcEnum skill_category_enum = {
    "SkillCategory", skill_category_values,
    sizeof(skill_category_values) / sizeof(skill_category_values[0]) };

#endif
