#ifndef ENUM_SPELL_ATTR3_H
#define ENUM_SPELL_ATTR3_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr3 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr3_values[] = {
    { 0x00000001, "Unknown attribute 0"                        },
    { 0x00000002, "Ignore Proc Subclass Mask"                  },
    { 0x00000004, "Unknown attribute 2"                        },
    { 0x00000008, "Completely Blocked"                         },
    { 0x00000010, "Ignore resurrection timer"                  },
    { 0x00000020, "Unknown attribute 5"                        },
    { 0x00000040, "Unknown attribute 6"                        },
    { 0x00000080, "Stack separately for each caster"           },
    { 0x00000100, "Can only target players"                    },
    { 0x00000200, "Not a Proc"                                 },
    { 0x00000400, "Require main hand weapon"                   },
    { 0x00000800, "Can only be cast in battleground"           },
    { 0x00001000, "Can only target ghost players"              },
    { 0x00002000, "Do not display channel bar (client only)"   },
    { 0x00004000, "Honorless Target"                           },
    { 0x00008000, "Unknown attribute 15"                       },
    { 0x00010000, "Cannot trigger procs"                       },
    { 0x00020000, "No initial aggro"                           },
    { 0x00040000, "Ignore hit result"                          },
    { 0x00080000, "Cannot trigger spells during aura proc"     },
    { 0x00100000, "Persists through death"                     },
    { 0x00200000, "Unknown attribute 21"                       },
    { 0x00400000, "Requires equipped Wand"                     },
    { 0x00800000, "Unknown attribute 23"                       },
    { 0x01000000, "Requires offhand weapon"                    },
    { 0x02000000, "Treat as periodic effect"                   },
    { 0x04000000, "Can Proc From Procs"                        },
    { 0x08000000, "Drain Soul"                                 },
    { 0x10000000, "Unknown attribute 28"                       },
    { 0x20000000, "Damage dealt is unaffected by modifiers"    },
    { 0x40000000, "Do not show range in tooltip (client only)" },
    { 0x80000000, "Unknown attribute 31"                       },
};

static const DbcEnum spell_attr3_enum = {
    "SpellAttr3", spell_attr3_values,
    sizeof(spell_attr3_values) / sizeof(spell_attr3_values[0]) };

#endif
