#ifndef ENUM_ACHIEVEMENT_CRITERIA_FLAGS_H
#define ENUM_ACHIEVEMENT_CRITERIA_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (AchievementCriteriaFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue achievement_criteria_flags_values[] = {
    { 0x00000001, "Show Progress Bar" },
    { 0x00000002, "Hidden"            },
    { 0x00000004, "Fail Achievement"  },
    { 0x00000008, "Reset On Start"    },
    { 0x00000010, "Is Date"           },
    { 0x00000020, "Money Counter"     },
};

static const DbcEnum achievement_criteria_flags_enum = {
    "AchievementCriteriaFlags", achievement_criteria_flags_values,
    sizeof(achievement_criteria_flags_values) / sizeof(achievement_criteria_flags_values[0]) };

#endif
