#ifndef ENUM_SPELL_ATTR5_H
#define ENUM_SPELL_ATTR5_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr5 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr5_values[] = {
    { 0x00000001, "Can be channeled while moving"                                },
    { 0x00000002, "No reagents during arena preparation"                         },
    { 0x00000004, "Remove when entering arena"                                   },
    { 0x00000008, "Usable while stunned"                                         },
    { 0x00000010, "Unknown attribute 4"                                          },
    { 0x00000020, "Single-target aura"                                           },
    { 0x00000040, "Unknown attribute 6"                                          },
    { 0x00000080, "Unknown attribute 7"                                          },
    { 0x00000100, "Cannot target player controlled units but can target players" },
    { 0x00000200, "Immediately do periodic tick on apply"                        },
    { 0x00000400, "Do not send aura duration to client"                          },
    { 0x00000800, "Auto-target target of target (client only)"                   },
    { 0x00001000, "Unknown attribute 12"                                         },
    { 0x00002000, "Duration scales with Haste Rating"                            },
    { 0x00004000, "Charmed units cannot cast this spell"                         },
    { 0x00008000, "Unknown attribute 15"                                         },
    { 0x00010000, "Unknown attribute 16"                                         },
    { 0x00020000, "Usable while feared"                                          },
    { 0x00040000, "Usable while confused"                                        },
    { 0x00080000, "Do not auto-turn while casting"                               },
    { 0x00100000, "Unknown attribute 20"                                         },
    { 0x00200000, "Unknown attribute 21"                                         },
    { 0x00400000, "Unknown attribute 22"                                         },
    { 0x00800000, "Unknown attribute 23"                                         },
    { 0x01000000, "Unknown attribute 24"                                         },
    { 0x02000000, "Unknown attribute 25"                                         },
    { 0x04000000, "Ignore line of sight checks"                                  },
    { 0x08000000, "Don't show aura if self-cast (client only)"                   },
    { 0x10000000, "Don't show aura unless self-cast (client only)"               },
    { 0x20000000, "Unknown attribute 29"                                         },
    { 0x40000000, "Unknown attribute 30"                                         },
    { 0x80000000, "Unknown attribute 31"                                         },
};

static const DbcEnum spell_attr5_enum = {
    "SpellAttr5", spell_attr5_values,
    sizeof(spell_attr5_values) / sizeof(spell_attr5_values[0]) };

#endif
