#ifndef ENUM_CHARACTER_FLAGS_H
#define ENUM_CHARACTER_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (CharacterFlags in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue character_flags_values[] = {
    { 0x00000001, "Flag Unk1"              },
    { 0x00000002, "Flag Unk2"              },
    { 0x00000004, "Locked For Transfer"    },
    { 0x00000008, "Flag Unk4"              },
    { 0x00000010, "Flag Unk5"              },
    { 0x00000020, "Flag Unk6"              },
    { 0x00000040, "Flag Unk7"              },
    { 0x00000080, "Flag Unk8"              },
    { 0x00000100, "Flag Unk9"              },
    { 0x00000200, "Flag Unk10"             },
    { 0x00000400, "Flag Hide Helm"         },
    { 0x00000800, "Flag Hide Cloak"        },
    { 0x00001000, "Flag Unk13"             },
    { 0x00002000, "Flag Ghost"             },
    { 0x00004000, "Flag Rename"            },
    { 0x00008000, "Flag Unk16"             },
    { 0x00010000, "Flag Unk17"             },
    { 0x00020000, "Flag Unk18"             },
    { 0x00040000, "Flag Unk19"             },
    { 0x00080000, "Flag Unk20"             },
    { 0x00100000, "Flag Unk21"             },
    { 0x00200000, "Flag Unk22"             },
    { 0x00400000, "Flag Unk23"             },
    { 0x00800000, "Flag Unk24"             },
    { 0x01000000, "Flag Locked By Billing" },
    { 0x02000000, "Flag Declined"          },
    { 0x04000000, "Flag Unk27"             },
    { 0x08000000, "Flag Unk28"             },
    { 0x10000000, "Flag Unk29"             },
    { 0x20000000, "Flag Unk30"             },
    { 0x40000000, "Flag Unk31"             },
    { 0x80000000, "Flag Unk32"             },
};

static const DbcEnum character_flags_enum = {
    "CharacterFlags", character_flags_values,
    sizeof(character_flags_values) / sizeof(character_flags_values[0]) };

#endif
