#ifndef ENUM_TOTEM_CATEGORY_H
#define ENUM_TOTEM_CATEGORY_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (TotemCategory in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue totem_category_values[] = {
    {          1, "Skinning Skife Old"    },
    {          2, "Earth Totem"           },
    {          3, "Air Totem"             },
    {          4, "Fire Totem"            },
    {          5, "Water Totem"           },
    {          6, "Copper Rod"            },
    {          7, "Silver Rod"            },
    {          8, "Golden Rod"            },
    {          9, "Truesilver Rod"        },
    {         10, "Arcanite Rod"          },
    {         11, "Mining Pick Old"       },
    {         12, "Philosophers Stone"    },
    {         13, "Blacksmith Hammer Old" },
    {         14, "Arclight Spanner"      },
    {         15, "Gyromatic Ma"          },
    {         21, "Master Totem"          },
    {         41, "Fel Iron Rod"          },
    {         62, "Adamantite Rod"        },
    {         63, "Eternium Rod"          },
    {         81, "Hollow Quill"          },
    {        101, "Runed Azurite Rod"     },
    {        121, "Virtuoso Inking Set"   },
    {        141, "Drums"                 },
    {        161, "Gnomish Army Knife"    },
    {        162, "Blacksmith Hammer"     },
    {        165, "Mining Pick"           },
    {        166, "Skinning Knife"        },
    {        167, "Hammer Pick"           },
    {        168, "Bladed Pickaxe"        },
    {        169, "Flint And Tinder"      },
    {        189, "Runed Cobalt Rod"      },
    {        190, "Runed Titanium Rod"    },
};

static const DbcEnum totem_category_enum = {
    "TotemCategory", totem_category_values,
    sizeof(totem_category_values) / sizeof(totem_category_values[0]) };

#endif
