#ifndef ENUM_SKILL_RACE_CLASS_INFO_FLAGS_H
#define ENUM_SKILL_RACE_CLASS_INFO_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SkillRaceClassInfoFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue skill_race_class_info_flags_values[] = {
    { 0x00000002, "No Skillup Message" },
    { 0x00000010, "Always Max Value"   },
    { 0x00000020, "Unlearnable"        },
    { 0x00000080, "Include In Sort"    },
    { 0x00000100, "Not Trainable"      },
    { 0x00000400, "Mono Value"         },
};

static const DbcEnum skill_race_class_info_flags_enum = {
    "SkillRaceClassInfoFlags", skill_race_class_info_flags_values,
    sizeof(skill_race_class_info_flags_values) / sizeof(skill_race_class_info_flags_values[0]) };

#endif
