#ifndef ENUM_CREATURE_TYPE_FLAGS_H
#define ENUM_CREATURE_TYPE_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (CreatureTypeFlags in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue creature_type_flags_values[] = {
    { 0x00000001, "Tameable"                          },
    { 0x00000002, "Visible To Ghosts"                 },
    { 0x00000004, "Boss Mob"                          },
    { 0x00000008, "Do Not Play Wound Anim"            },
    { 0x00000010, "No Faction Tooltip"                },
    { 0x00000020, "More Audible"                      },
    { 0x00000040, "Spell Attackable"                  },
    { 0x00000080, "Interact While Dead"               },
    { 0x00000100, "Skin With Herbalism"               },
    { 0x00000200, "Skin With Mining"                  },
    { 0x00000400, "No Death Message"                  },
    { 0x00000800, "Allow Mounted Combat"              },
    { 0x00001000, "Can Assist"                        },
    { 0x00002000, "No Pet Bar"                        },
    { 0x00004000, "Mask Uid"                          },
    { 0x00008000, "Skin With Engineering"             },
    { 0x00010000, "Tameable Exotic"                   },
    { 0x00020000, "Use Model Collision Size"          },
    { 0x00040000, "Allow Interaction While In Combat" },
    { 0x00080000, "Collide With Missiles"             },
    { 0x00100000, "No Name Plate"                     },
    { 0x00200000, "Do Not Play Mounted Animations"    },
    { 0x00400000, "Link All"                          },
    { 0x00800000, "Interact Only With Creator"        },
    { 0x01000000, "Do Not Play Unit Event Sounds"     },
    { 0x02000000, "Has No Shadow Blob"                },
    { 0x04000000, "Treat As Raid Unit"                },
    { 0x08000000, "Force Gossip"                      },
    { 0x10000000, "Do Not Sheathe"                    },
    { 0x20000000, "Do Not Target On Interaction"      },
    { 0x40000000, "Do Not Render Object Name"         },
    { 0x80000000, "Quest Boss"                        },
};

static const DbcEnum creature_type_flags_enum = {
    "CreatureTypeFlags", creature_type_flags_values,
    sizeof(creature_type_flags_values) / sizeof(creature_type_flags_values[0]) };

#endif
