#ifndef ENUM_AREA_FLAGS_H
#define ENUM_AREA_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (AreaFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue area_flags_values[] = {
    { 0x00000001, "Unk0"               },
    { 0x00000002, "Unk1"               },
    { 0x00000004, "Unk2"               },
    { 0x00000008, "Slave Capital"      },
    { 0x00000010, "Unk3"               },
    { 0x00000020, "Slave Capital2"     },
    { 0x00000040, "Allow Duels"        },
    { 0x00000080, "Arena"              },
    { 0x00000100, "Capital"            },
    { 0x00000200, "City"               },
    { 0x00000400, "Outland"            },
    { 0x00000800, "Sanctuary"          },
    { 0x00001000, "Need Fly"           },
    { 0x00002000, "Unused1"            },
    { 0x00004000, "Outland2"           },
    { 0x00008000, "Outdoor Pvp"        },
    { 0x00010000, "Arena Instance"     },
    { 0x00020000, "Unused2"            },
    { 0x00040000, "Contested Area"     },
    { 0x00080000, "Unk4"               },
    { 0x00100000, "Lowlevel"           },
    { 0x00200000, "Town"               },
    { 0x00400000, "Rest Zone Horde"    },
    { 0x00800000, "Rest Zone Alliance" },
    { 0x01000000, "Wintergrasp"        },
    { 0x02000000, "Inside"             },
    { 0x04000000, "Outside"            },
    { 0x08000000, "Wintergrasp 2"      },
    { 0x20000000, "No Fly Zone"        },
};

static const DbcEnum area_flags_enum = {
    "AreaFlags", area_flags_values,
    sizeof(area_flags_values) / sizeof(area_flags_values[0]) };

#endif
