#ifndef ENUM_ITEM_FLAGS_H
#define ENUM_ITEM_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (ItemFlags in src/server/game/Entities/Item/ItemTemplate.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue item_flags_values[] = {
    { 0x00000001, "No Pickup"                         },
    { 0x00000002, "Conjured"                          },
    { 0x00000004, "Has Loot"                          },
    { 0x00000008, "Heroic Tooltip"                    },
    { 0x00000010, "Deprecated"                        },
    { 0x00000020, "No User Destroy"                   },
    { 0x00000040, "Playercast"                        },
    { 0x00000080, "No Equip Cooldown"                 },
    { 0x00000100, "Multi Loot Quest"                  },
    { 0x00000200, "Is Wrapper"                        },
    { 0x00000400, "Uses Resources"                    },
    { 0x00000800, "Multi Drop"                        },
    { 0x00001000, "Item Purchase Record"              },
    { 0x00002000, "Petition"                          },
    { 0x00004000, "Has Text"                          },
    { 0x00008000, "No Disenchant"                     },
    { 0x00010000, "Real Duration"                     },
    { 0x00020000, "No Creator"                        },
    { 0x00040000, "Is Prospectable"                   },
    { 0x00080000, "Unique Equippable"                 },
    { 0x00100000, "Ignore For Auras"                  },
    { 0x00200000, "Ignore Default Arena Restrictions" },
    { 0x00400000, "No Durability Loss"                },
    { 0x00800000, "Use When Shapeshifted"             },
    { 0x01000000, "Has Quest Glow"                    },
    { 0x02000000, "Hide Unusable Recipe"              },
    { 0x04000000, "Not Useable In Arena"              },
    { 0x08000000, "Is Bound To Account"               },
    { 0x10000000, "No Reagent Cost"                   },
    { 0x20000000, "Is Millable"                       },
    { 0x40000000, "Report To Guild Chat"              },
    { 0x80000000, "No Progressive Loot"               },
};

static const DbcEnum item_flags_enum = {
    "ItemFlags", item_flags_values,
    sizeof(item_flags_values) / sizeof(item_flags_values[0]) };

#endif
