#ifndef ENUM_FACTION_TEMPLATE_FLAGS_H
#define ENUM_FACTION_TEMPLATE_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (FactionTemplateFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue faction_template_flags_values[] = {
    { 0x00000800, "Pvp"                },
    { 0x00001000, "Contested Guard"    },
    { 0x00002000, "Hostile By Default" },
};

static const DbcEnum faction_template_flags_enum = {
    "FactionTemplateFlags", faction_template_flags_values,
    sizeof(faction_template_flags_values) / sizeof(faction_template_flags_values[0]) };

#endif
