#ifndef ENUM_SPELL_ATTR6_H
#define ENUM_SPELL_ATTR6_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (SpellAttr6 in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue spell_attr6_values[] = {
    { 0x00000001, "Don't display cooldown (client only)"                          },
    { 0x00000002, "Only usable in arena"                                          },
    { 0x00000004, "Ignore all preventing caster auras"                            },
    { 0x00000008, "Ignore immunity flags when assisting"                          },
    { 0x00000010, "Unknown attribute 4"                                           },
    { 0x00000020, "Don't consume proc charges"                                    },
    { 0x00000040, "Generate spell_cast event instead of aura_start (client only)" },
    { 0x00000080, "Unknown attribute 7"                                           },
    { 0x00000100, "Do not implicitly target in CC"                                },
    { 0x00000200, "Unknown attribute 9"                                           },
    { 0x00000400, "Can target possessed friends"                                  },
    { 0x00000800, "Unusable in raid instances"                                    },
    { 0x00001000, "Castable while caster is on vehicle"                           },
    { 0x00002000, "Can target invisible units"                                    },
    { 0x00004000, "Unknown attribute 14"                                          },
    { 0x00008000, "Unknown attribute 15"                                          },
    { 0x00010000, "Unknown attribute 16"                                          },
    { 0x00020000, "Unknown attribute 17"                                          },
    { 0x00040000, "Spell is cast by charmer"                                      },
    { 0x00080000, "Unknown attribute 19"                                          },
    { 0x00100000, "Only visible to caster (client only)"                          },
    { 0x00200000, "Client UI target effects (client only)"                        },
    { 0x00400000, "Unknown attribute 22"                                          },
    { 0x00800000, "Unknown attribute 23"                                          },
    { 0x01000000, "Can target untargetable units"                                 },
    { 0x02000000, "Do not reset swing timer if cast time is instant"              },
    { 0x04000000, "Unknown attribute 26"                                          },
    { 0x08000000, "Limit applicable %healing modifiers"                           },
    { 0x10000000, "Unknown attribute 28"                                          },
    { 0x20000000, "Limit applicable %damage modifiers"                            },
    { 0x40000000, "Unknown attribute 30"                                          },
    { 0x80000000, "Ignore cooldown modifiers for category cooldown"               },
};

static const DbcEnum spell_attr6_enum = {
    "SpellAttr6", spell_attr6_values,
    sizeof(spell_attr6_values) / sizeof(spell_attr6_values[0]) };

#endif
