#ifndef ENUM_VEHICLE_SEAT_FLAGS_B_H
#define ENUM_VEHICLE_SEAT_FLAGS_B_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (VehicleSeatFlagsB in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue vehicle_seat_flags_b_values[] = {
    { 0x00000002, "Usable Forced"          },
    { 0x00000008, "Targets In Raidui"      },
    { 0x00000020, "Ejectable"              },
    { 0x00000040, "Usable Forced 2"        },
    { 0x00000100, "Usable Forced 3"        },
    { 0x00020000, "Keep Pet"               },
    { 0x02000000, "Usable Forced 4"        },
    { 0x04000000, "Can Switch"             },
    { 0x80000000, "Vehicle Playerframe Ui" },
};

static const DbcEnum vehicle_seat_flags_b_enum = {
    "VehicleSeatFlagsB", vehicle_seat_flags_b_values,
    sizeof(vehicle_seat_flags_b_values) / sizeof(vehicle_seat_flags_b_values[0]) };

#endif
