#ifndef ENUM_UNIT_DYN_FLAGS_H
#define ENUM_UNIT_DYN_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (UnitDynFlags in src/server/shared/SharedDefines.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue unit_dyn_flags_values[] = {
    { 0x00000001, "Lootable"                  },
    { 0x00000002, "Track Unit"                },
    { 0x00000004, "Tapped"                    },
    { 0x00000008, "Tapped By Player"          },
    { 0x00000010, "Specialinfo"               },
    { 0x00000020, "Dead"                      },
    { 0x00000040, "Refer A Friend"            },
    { 0x00000080, "Tapped By All Threat List" },
};

static const DbcEnum unit_dyn_flags_enum = {
    "UnitDynFlags", unit_dyn_flags_values,
    sizeof(unit_dyn_flags_values) / sizeof(unit_dyn_flags_values[0]) };

#endif
