#ifndef ENUM_MAP_FLAGS_H
#define ENUM_MAP_FLAGS_H

#include "dbc_enum.h"

// Extracted from TrinityCore 3.3.5 (MapFlags in src/server/shared/DataStores/DBCEnums.h).
// Generated by tools/extract_tc_enums.py -- re-run to refresh.
//
// Each entry is (bit value, display label). Labels are derived from
// the SCREAMING_SNAKE source name with the common prefix stripped.
static const DbcEnumValue map_flags_values[] = {
    { 0x00000100, "Map Flag Dynamic Difficulty" },
};

static const DbcEnum map_flags_enum = {
    "MapFlags", map_flags_values,
    sizeof(map_flags_values) / sizeof(map_flags_values[0]) };

#endif
