#ifndef SCHEMA_MAP_H
#define SCHEMA_MAP_H

#include "dbc_schema.h"

static const DbcFieldDef map_fields[] = {
    { "Id",                         DbcFieldType::UInt32 },
    { "Directory",                  DbcFieldType::String },
    { "InstanceType",               DbcFieldType::UInt32 },
    { "Flags",                      DbcFieldType::UInt32 },
    { "MapType",                    DbcFieldType::UInt32 },
    { "MapName_enUS",               DbcFieldType::String },
    { "MapName_koKR",               DbcFieldType::String },
    { "MapName_frFR",               DbcFieldType::String },
    { "MapName_deDE",               DbcFieldType::String },
    { "MapName_enCN",               DbcFieldType::String },
    { "MapName_zhTW",               DbcFieldType::String },
    { "MapName_esES",               DbcFieldType::String },
    { "MapName_esMX",               DbcFieldType::String },
    { "MapName_ruRU",               DbcFieldType::String },
    { "MapName_jaJP",               DbcFieldType::String },
    { "MapName_ptPT",               DbcFieldType::String },
    { "MapName_itIT",               DbcFieldType::String },
    { "MapName_Unk1",               DbcFieldType::String },
    { "MapName_Unk2",               DbcFieldType::String },
    { "MapName_Unk3",               DbcFieldType::String },
    { "MapName_Unk4",               DbcFieldType::String },
    { "MapNameFlags",               DbcFieldType::UInt32 },
    { "AreaTableID",                DbcFieldType::UInt32 },
    { "MapDescription0_enUS",       DbcFieldType::String },
    { "MapDescription0_koKR",       DbcFieldType::String },
    { "MapDescription0_frFR",       DbcFieldType::String },
    { "MapDescription0_deDE",       DbcFieldType::String },
    { "MapDescription0_enCN",       DbcFieldType::String },
    { "MapDescription0_zhTW",       DbcFieldType::String },
    { "MapDescription0_esES",       DbcFieldType::String },
    { "MapDescription0_esMX",       DbcFieldType::String },
    { "MapDescription0_ruRU",       DbcFieldType::String },
    { "MapDescription0_jaJP",       DbcFieldType::String },
    { "MapDescription0_ptPT",       DbcFieldType::String },
    { "MapDescription0_itIT",       DbcFieldType::String },
    { "MapDescription0_Unk1",       DbcFieldType::String },
    { "MapDescription0_Unk2",       DbcFieldType::String },
    { "MapDescription0_Unk3",       DbcFieldType::String },
    { "MapDescription0_Unk4",       DbcFieldType::String },
    { "MapDescription0Flags",       DbcFieldType::UInt32 },
    { "MapDescription1_enUS",       DbcFieldType::String },
    { "MapDescription1_koKR",       DbcFieldType::String },
    { "MapDescription1_frFR",       DbcFieldType::String },
    { "MapDescription1_deDE",       DbcFieldType::String },
    { "MapDescription1_enCN",       DbcFieldType::String },
    { "MapDescription1_zhTW",       DbcFieldType::String },
    { "MapDescription1_esES",       DbcFieldType::String },
    { "MapDescription1_esMX",       DbcFieldType::String },
    { "MapDescription1_ruRU",       DbcFieldType::String },
    { "MapDescription1_jaJP",       DbcFieldType::String },
    { "MapDescription1_ptPT",       DbcFieldType::String },
    { "MapDescription1_itIT",       DbcFieldType::String },
    { "MapDescription1_Unk1",       DbcFieldType::String },
    { "MapDescription1_Unk2",       DbcFieldType::String },
    { "MapDescription1_Unk3",       DbcFieldType::String },
    { "MapDescription1_Unk4",       DbcFieldType::String },
    { "MapDescription1Flags",       DbcFieldType::UInt32 },
    { "LoadingScreen",              DbcFieldType::UInt32 },
    { "MinimapIconScale",           DbcFieldType::Float  },
    { "CorpseMapID",                DbcFieldType::Int32  },
    { "CorpseEntranceX",            DbcFieldType::Float  },
    { "CorpseEntranceY",            DbcFieldType::Float  },
    { "TimeOfDayOverride",          DbcFieldType::Int32  },
    { "ExpansionID",                DbcFieldType::UInt32 },
    { "RaidOffset",                 DbcFieldType::UInt32 },
    { "MaxPlayers",                 DbcFieldType::UInt32 },
};

static const DbcSchema schema_map = {
    "Map",
    map_fields,
    sizeof(map_fields) / sizeof(map_fields[0])
};

#endif // SCHEMA_MAP_H
