#ifndef SCHEMA_CHR_CLASSES_H
#define SCHEMA_CHR_CLASSES_H

#include "dbc_schema.h"

static const DbcFieldDef chr_classes_fields[] = {
    { "Id",                    DbcFieldType::UInt32 },
    { "Unknown1",              DbcFieldType::UInt32 },
    { "PowerType",             DbcFieldType::UInt32 },
    { "PetNameToken",          DbcFieldType::String },
    { "Name_enUS",             DbcFieldType::String },
    { "Name_koKR",             DbcFieldType::String },
    { "Name_frFR",             DbcFieldType::String },
    { "Name_deDE",             DbcFieldType::String },
    { "Name_enCN",             DbcFieldType::String },
    { "Name_zhTW",             DbcFieldType::String },
    { "Name_esES",             DbcFieldType::String },
    { "Name_esMX",             DbcFieldType::String },
    { "Name_ruRU",             DbcFieldType::String },
    { "Name_jaJP",             DbcFieldType::String },
    { "Name_ptPT",             DbcFieldType::String },
    { "Name_itIT",             DbcFieldType::String },
    { "Name_Unk1",             DbcFieldType::String },
    { "Name_Unk2",             DbcFieldType::String },
    { "Name_Unk3",             DbcFieldType::String },
    { "Name_Unk4",             DbcFieldType::String },
    { "NameFlags",             DbcFieldType::UInt32 },
    { "NameFemale_enUS",       DbcFieldType::String },
    { "NameFemale_koKR",       DbcFieldType::String },
    { "NameFemale_frFR",       DbcFieldType::String },
    { "NameFemale_deDE",       DbcFieldType::String },
    { "NameFemale_enCN",       DbcFieldType::String },
    { "NameFemale_zhTW",       DbcFieldType::String },
    { "NameFemale_esES",       DbcFieldType::String },
    { "NameFemale_esMX",       DbcFieldType::String },
    { "NameFemale_ruRU",       DbcFieldType::String },
    { "NameFemale_jaJP",       DbcFieldType::String },
    { "NameFemale_ptPT",       DbcFieldType::String },
    { "NameFemale_itIT",       DbcFieldType::String },
    { "NameFemale_Unk1",       DbcFieldType::String },
    { "NameFemale_Unk2",       DbcFieldType::String },
    { "NameFemale_Unk3",       DbcFieldType::String },
    { "NameFemale_Unk4",       DbcFieldType::String },
    { "NameFemaleFlags",       DbcFieldType::UInt32 },
    { "NameMale_enUS",         DbcFieldType::String },
    { "NameMale_koKR",         DbcFieldType::String },
    { "NameMale_frFR",         DbcFieldType::String },
    { "NameMale_deDE",         DbcFieldType::String },
    { "NameMale_enCN",         DbcFieldType::String },
    { "NameMale_zhTW",         DbcFieldType::String },
    { "NameMale_esES",         DbcFieldType::String },
    { "NameMale_esMX",         DbcFieldType::String },
    { "NameMale_ruRU",         DbcFieldType::String },
    { "NameMale_jaJP",         DbcFieldType::String },
    { "NameMale_ptPT",         DbcFieldType::String },
    { "NameMale_itIT",         DbcFieldType::String },
    { "NameMale_Unk1",         DbcFieldType::String },
    { "NameMale_Unk2",         DbcFieldType::String },
    { "NameMale_Unk3",         DbcFieldType::String },
    { "NameMale_Unk4",         DbcFieldType::String },
    { "NameMaleFlags",         DbcFieldType::UInt32 },
    { "Filename",              DbcFieldType::String },
    { "SpellClassSet",         DbcFieldType::UInt32 },
    { "Flags",                 DbcFieldType::UInt32 },
    { "CinematicSequenceID",   DbcFieldType::UInt32 },
    { "RequiredExpansion",     DbcFieldType::UInt32 },
};

static const DbcSchema schema_chr_classes = {
    "ChrClasses",
    chr_classes_fields,
    sizeof(chr_classes_fields) / sizeof(chr_classes_fields[0])
};

#endif
