#ifndef SCHEMA_MAP_H
#define SCHEMA_MAP_H

#include "dbc_schema.h"

static const DbcFieldDef map_fields[] = {
    { "Id",                         DbcFieldType::UInt32 },
    { "Directory",                  DbcFieldType::String },
    { "InstanceType",               DbcFieldType::UInt32 },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "MapFlags" },
    { "MapType",                    DbcFieldType::UInt32 },
    { "MapName_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapName_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName" },
    { "MapNameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "AreaTableID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "areatable" },
    { "MapDescription0_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0" },
    { "MapDescription0Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "MapDescription1_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1" },
    { "MapDescription1Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "LoadingScreen",              DbcFieldType::UInt32 },
    { "MinimapIconScale",           DbcFieldType::Float  },
    { "CorpseMapID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "corpsemap" },
    { "CorpseEntranceX",            DbcFieldType::Float  },
    { "CorpseEntranceY",            DbcFieldType::Float  },
    { "TimeOfDayOverride",          DbcFieldType::Int32  },
    { "ExpansionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "expansion" },
    { "RaidOffset",                 DbcFieldType::UInt32 },
    { "MaxPlayers",                 DbcFieldType::UInt32 },
};

static const DbcSchema schema_map = {
    "Map",
    map_fields,
    sizeof(map_fields) / sizeof(map_fields[0])
};

#endif // SCHEMA_MAP_H
