#ifndef SCHEMA_MAP_H
#define SCHEMA_MAP_H

#include "dbc_schema.h"

static const DbcFieldDef map_fields[] = {
    { "Id", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Identity" },
    { "Directory", DbcFieldType::String },
    { "InstanceType", DbcFieldType::UInt32 },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "MapFlags", "Classification" },
    { "MapType", DbcFieldType::UInt32 },
    { "MapName_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapName_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapName", "Identity" },
    { "MapNameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "AreaTableID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "areatable" },
    { "MapDescription0_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription0", "Identity" },
    { "MapDescription0Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "MapDescription1_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "MapDescription1", "Identity" },
    { "MapDescription1Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "LoadingScreen", DbcFieldType::UInt32 },
    { "MinimapIconScale", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Visuals" },
    { "CorpseMapID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "corpsemap" },
    { "CorpseEntranceX", DbcFieldType::Float },
    { "CorpseEntranceY", DbcFieldType::Float },
    { "TimeOfDayOverride", DbcFieldType::Int32 },
    { "ExpansionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "expansion" },
    { "RaidOffset", DbcFieldType::UInt32 },
    { "MaxPlayers", DbcFieldType::UInt32 },
};

static const DbcSchema schema_map = {
    "Map",
    map_fields,
    sizeof(map_fields) / sizeof(map_fields[0])
};

#endif // SCHEMA_MAP_H
