#ifndef SCHEMA_WORLD_STATE_UI_H
#define SCHEMA_WORLD_STATE_UI_H

#include "dbc_schema.h"

static const DbcFieldDef world_state_ui_fields[] = {
    { "Id",                    DbcFieldType::UInt32 },
    { "MapID",                 DbcFieldType::UInt32 },
    { "AreaID",                DbcFieldType::UInt32 },
    { "PhaseShift",            DbcFieldType::UInt32 },
    { "Icon",                  DbcFieldType::String },
    { "String_enUS",           DbcFieldType::String },
    { "String_koKR",           DbcFieldType::String },
    { "String_frFR",           DbcFieldType::String },
    { "String_deDE",           DbcFieldType::String },
    { "String_enCN",           DbcFieldType::String },
    { "String_zhTW",           DbcFieldType::String },
    { "String_esES",           DbcFieldType::String },
    { "String_esMX",           DbcFieldType::String },
    { "String_ruRU",           DbcFieldType::String },
    { "String_jaJP",           DbcFieldType::String },
    { "String_ptPT",           DbcFieldType::String },
    { "String_itIT",           DbcFieldType::String },
    { "String_Unk1",           DbcFieldType::String },
    { "String_Unk2",           DbcFieldType::String },
    { "String_Unk3",           DbcFieldType::String },
    { "String_Unk4",           DbcFieldType::String },
    { "StringFlags",           DbcFieldType::UInt32 },
    { "Tooltip_enUS",          DbcFieldType::String },
    { "Tooltip_koKR",          DbcFieldType::String },
    { "Tooltip_frFR",          DbcFieldType::String },
    { "Tooltip_deDE",          DbcFieldType::String },
    { "Tooltip_enCN",          DbcFieldType::String },
    { "Tooltip_zhTW",          DbcFieldType::String },
    { "Tooltip_esES",          DbcFieldType::String },
    { "Tooltip_esMX",          DbcFieldType::String },
    { "Tooltip_ruRU",          DbcFieldType::String },
    { "Tooltip_jaJP",          DbcFieldType::String },
    { "Tooltip_ptPT",          DbcFieldType::String },
    { "Tooltip_itIT",          DbcFieldType::String },
    { "Tooltip_Unk1",          DbcFieldType::String },
    { "Tooltip_Unk2",          DbcFieldType::String },
    { "Tooltip_Unk3",          DbcFieldType::String },
    { "Tooltip_Unk4",          DbcFieldType::String },
    { "TooltipFlags",          DbcFieldType::UInt32 },
    { "DynamicIcon",           DbcFieldType::String },
    { "DynamicTooltip_enUS",   DbcFieldType::String },
    { "DynamicTooltip_koKR",   DbcFieldType::String },
    { "DynamicTooltip_frFR",   DbcFieldType::String },
    { "DynamicTooltip_deDE",   DbcFieldType::String },
    { "DynamicTooltip_enCN",   DbcFieldType::String },
    { "DynamicTooltip_zhTW",   DbcFieldType::String },
    { "DynamicTooltip_esES",   DbcFieldType::String },
    { "DynamicTooltip_esMX",   DbcFieldType::String },
    { "DynamicTooltip_ruRU",   DbcFieldType::String },
    { "DynamicTooltip_jaJP",   DbcFieldType::String },
    { "DynamicTooltip_ptPT",   DbcFieldType::String },
    { "DynamicTooltip_itIT",   DbcFieldType::String },
    { "DynamicTooltip_Unk1",   DbcFieldType::String },
    { "DynamicTooltip_Unk2",   DbcFieldType::String },
    { "DynamicTooltip_Unk3",   DbcFieldType::String },
    { "DynamicTooltip_Unk4",   DbcFieldType::String },
    { "DynamicTooltipFlags",   DbcFieldType::UInt32 },
    { "ExtendedUI",            DbcFieldType::String },
    { "ExtendedUIStateVar1",   DbcFieldType::UInt32 },
    { "ExtendedUIStateVar2",   DbcFieldType::UInt32 },
    { "ExtendedUIStateVar3",   DbcFieldType::UInt32 },
    { "Type",                  DbcFieldType::UInt32 },
    { "OrderIndex",            DbcFieldType::UInt32 },
};

static const DbcSchema schema_world_state_ui = {
    "WorldStateUI",
    world_state_ui_fields,
    sizeof(world_state_ui_fields) / sizeof(world_state_ui_fields[0])
};

#endif
