#ifndef SCHEMA_ACHIEVEMENT_H
#define SCHEMA_ACHIEVEMENT_H

#include "dbc_schema.h"

static const DbcFieldDef achievement_fields[] = {
    { "Id",                  DbcFieldType::UInt32 },
    { "Faction",             DbcFieldType::Int32  },
    { "MapID",               DbcFieldType::Int32  },
    { "PreviousAchievement", DbcFieldType::UInt32 },
    { "Name_enUS",           DbcFieldType::String },
    { "Name_koKR",           DbcFieldType::String },
    { "Name_frFR",           DbcFieldType::String },
    { "Name_deDE",           DbcFieldType::String },
    { "Name_enCN",           DbcFieldType::String },
    { "Name_zhTW",           DbcFieldType::String },
    { "Name_esES",           DbcFieldType::String },
    { "Name_esMX",           DbcFieldType::String },
    { "Name_ruRU",           DbcFieldType::String },
    { "Name_jaJP",           DbcFieldType::String },
    { "Name_ptPT",           DbcFieldType::String },
    { "Name_itIT",           DbcFieldType::String },
    { "Name_Unk1",           DbcFieldType::String },
    { "Name_Unk2",           DbcFieldType::String },
    { "Name_Unk3",           DbcFieldType::String },
    { "Name_Unk4",           DbcFieldType::String },
    { "NameFlags",           DbcFieldType::UInt32 },
    { "Description_enUS",    DbcFieldType::String },
    { "Description_koKR",    DbcFieldType::String },
    { "Description_frFR",    DbcFieldType::String },
    { "Description_deDE",    DbcFieldType::String },
    { "Description_enCN",    DbcFieldType::String },
    { "Description_zhTW",    DbcFieldType::String },
    { "Description_esES",    DbcFieldType::String },
    { "Description_esMX",    DbcFieldType::String },
    { "Description_ruRU",    DbcFieldType::String },
    { "Description_jaJP",    DbcFieldType::String },
    { "Description_ptPT",    DbcFieldType::String },
    { "Description_itIT",    DbcFieldType::String },
    { "Description_Unk1",    DbcFieldType::String },
    { "Description_Unk2",    DbcFieldType::String },
    { "Description_Unk3",    DbcFieldType::String },
    { "Description_Unk4",    DbcFieldType::String },
    { "DescriptionFlags",    DbcFieldType::UInt32 },
    { "Category",            DbcFieldType::UInt32 },
    { "Points",              DbcFieldType::UInt32 },
    { "SortOrder",           DbcFieldType::UInt32 },
    { "Flags",               DbcFieldType::UInt32 },
    { "IconID",              DbcFieldType::UInt32 },
    { "Reward_enUS",         DbcFieldType::String },
    { "Reward_koKR",         DbcFieldType::String },
    { "Reward_frFR",         DbcFieldType::String },
    { "Reward_deDE",         DbcFieldType::String },
    { "Reward_enCN",         DbcFieldType::String },
    { "Reward_zhTW",         DbcFieldType::String },
    { "Reward_esES",         DbcFieldType::String },
    { "Reward_esMX",         DbcFieldType::String },
    { "Reward_ruRU",         DbcFieldType::String },
    { "Reward_jaJP",         DbcFieldType::String },
    { "Reward_ptPT",         DbcFieldType::String },
    { "Reward_itIT",         DbcFieldType::String },
    { "Reward_Unk1",         DbcFieldType::String },
    { "Reward_Unk2",         DbcFieldType::String },
    { "Reward_Unk3",         DbcFieldType::String },
    { "Reward_Unk4",         DbcFieldType::String },
    { "RewardFlags",         DbcFieldType::UInt32 },
    { "MinimumCriteria",     DbcFieldType::UInt32 },
    { "SharesCriteria",      DbcFieldType::UInt32 },
};

static const DbcSchema schema_achievement = {
    "Achievement",
    achievement_fields,
    sizeof(achievement_fields) / sizeof(achievement_fields[0])
};

#endif
