#ifndef SCHEMA_SPELL_H
#define SCHEMA_SPELL_H

#include "dbc_schema.h"

static const DbcFieldDef spell_fields[] = {
    { "Id",                         DbcFieldType::UInt32 },
    { "Category",                   DbcFieldType::UInt32 },
    { "Dispel",                     DbcFieldType::UInt32 },
    { "Mechanic",                   DbcFieldType::UInt32 },
    { "Attributes", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr0" },
    { "AttributesEx", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr1" },
    { "AttributesEx2", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr2" },
    { "AttributesEx3", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr3" },
    { "AttributesEx4", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr4" },
    { "AttributesEx5", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr5" },
    { "AttributesEx6", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr6" },
    { "AttributesEx7", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr7" },
    { "Stances",                    DbcFieldType::UInt32 },
    { "StancesHigh",                DbcFieldType::UInt32 },
    { "StancesNot",                 DbcFieldType::UInt32 },
    { "StancesNotHigh",             DbcFieldType::UInt32 },
    { "Targets",                    DbcFieldType::UInt32 },
    { "TargetCreatureType",         DbcFieldType::UInt32 },
    { "RequiresSpellFocus",         DbcFieldType::UInt32 },
    { "FacingCasterFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "CasterAuraState",            DbcFieldType::UInt32 },
    { "TargetAuraState",            DbcFieldType::UInt32 },
    { "CasterAuraStateNot",         DbcFieldType::UInt32 },
    { "TargetAuraStateNot",         DbcFieldType::UInt32 },
    { "CasterAuraSpell",            DbcFieldType::UInt32 },
    { "TargetAuraSpell",            DbcFieldType::UInt32 },
    { "ExcludeCasterAuraSpell",     DbcFieldType::UInt32 },
    { "ExcludeTargetAuraSpell",     DbcFieldType::UInt32 },
    { "CastingTimeIndex",           DbcFieldType::UInt32 },
    { "RecoveryTime",               DbcFieldType::UInt32 },
    { "CategoryRecoveryTime",       DbcFieldType::UInt32 },
    { "InterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "AuraInterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ChannelInterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ProcFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ProcChance",                 DbcFieldType::UInt32 },
    { "ProcCharges",                DbcFieldType::UInt32 },
    { "MaxLevel",                   DbcFieldType::UInt32 },
    { "BaseLevel",                  DbcFieldType::UInt32 },
    { "SpellLevel",                 DbcFieldType::UInt32 },
    { "DurationIndex",              DbcFieldType::UInt32 },
    { "PowerType", DbcFieldType::Int32, DbcSemantic::Enum, "PowerType" },
    { "ManaCost",                   DbcFieldType::UInt32 },
    { "ManaCostPerLevel",           DbcFieldType::UInt32 },
    { "ManaPerSecond",              DbcFieldType::UInt32 },
    { "ManaPerSecondPerLevel",      DbcFieldType::UInt32 },
    { "RangeIndex",                 DbcFieldType::UInt32 },
    { "Speed",                      DbcFieldType::Float  },
    { "ModalNextSpell",             DbcFieldType::UInt32 },
    { "StackAmount",                DbcFieldType::UInt32 },
    { "Totem1",                     DbcFieldType::UInt32 },
    { "Totem2",                     DbcFieldType::UInt32 },
    { "Reagent1",                   DbcFieldType::Int32  },
    { "Reagent2",                   DbcFieldType::Int32  },
    { "Reagent3",                   DbcFieldType::Int32  },
    { "Reagent4",                   DbcFieldType::Int32  },
    { "Reagent5",                   DbcFieldType::Int32  },
    { "Reagent6",                   DbcFieldType::Int32  },
    { "Reagent7",                   DbcFieldType::Int32  },
    { "Reagent8",                   DbcFieldType::Int32  },
    { "ReagentCount1",              DbcFieldType::UInt32 },
    { "ReagentCount2",              DbcFieldType::UInt32 },
    { "ReagentCount3",              DbcFieldType::UInt32 },
    { "ReagentCount4",              DbcFieldType::UInt32 },
    { "ReagentCount5",              DbcFieldType::UInt32 },
    { "ReagentCount6",              DbcFieldType::UInt32 },
    { "ReagentCount7",              DbcFieldType::UInt32 },
    { "ReagentCount8",              DbcFieldType::UInt32 },
    { "EquippedItemClass",          DbcFieldType::Int32  },
    { "EquippedItemSubClassMask", DbcFieldType::Int32, DbcSemantic::Bitmask },
    { "EquippedItemInventoryTypeMask", DbcFieldType::Int32, DbcSemantic::Bitmask },
    { "Effect1",                    DbcFieldType::UInt32 },
    { "Effect2",                    DbcFieldType::UInt32 },
    { "Effect3",                    DbcFieldType::UInt32 },
    { "EffectDieSides1",            DbcFieldType::Int32  },
    { "EffectDieSides2",            DbcFieldType::Int32  },
    { "EffectDieSides3",            DbcFieldType::Int32  },
    { "EffectRealPointsPerLevel1",  DbcFieldType::Float  },
    { "EffectRealPointsPerLevel2",  DbcFieldType::Float  },
    { "EffectRealPointsPerLevel3",  DbcFieldType::Float  },
    { "EffectBasePoints1",          DbcFieldType::Int32  },
    { "EffectBasePoints2",          DbcFieldType::Int32  },
    { "EffectBasePoints3",          DbcFieldType::Int32  },
    { "EffectMechanic1",            DbcFieldType::UInt32 },
    { "EffectMechanic2",            DbcFieldType::UInt32 },
    { "EffectMechanic3",            DbcFieldType::UInt32 },
    { "EffectImplicitTargetA1",     DbcFieldType::UInt32 },
    { "EffectImplicitTargetA2",     DbcFieldType::UInt32 },
    { "EffectImplicitTargetA3",     DbcFieldType::UInt32 },
    { "EffectImplicitTargetB1",     DbcFieldType::UInt32 },
    { "EffectImplicitTargetB2",     DbcFieldType::UInt32 },
    { "EffectImplicitTargetB3",     DbcFieldType::UInt32 },
    { "EffectRadiusIndex1",         DbcFieldType::UInt32 },
    { "EffectRadiusIndex2",         DbcFieldType::UInt32 },
    { "EffectRadiusIndex3",         DbcFieldType::UInt32 },
    { "EffectApplyAuraName1",       DbcFieldType::UInt32 },
    { "EffectApplyAuraName2",       DbcFieldType::UInt32 },
    { "EffectApplyAuraName3",       DbcFieldType::UInt32 },
    { "EffectAmplitude1",           DbcFieldType::UInt32 },
    { "EffectAmplitude2",           DbcFieldType::UInt32 },
    { "EffectAmplitude3",           DbcFieldType::UInt32 },
    { "EffectMultipleValue1",       DbcFieldType::Float  },
    { "EffectMultipleValue2",       DbcFieldType::Float  },
    { "EffectMultipleValue3",       DbcFieldType::Float  },
    { "EffectChainTarget1",         DbcFieldType::UInt32 },
    { "EffectChainTarget2",         DbcFieldType::UInt32 },
    { "EffectChainTarget3",         DbcFieldType::UInt32 },
    { "EffectItemType1",            DbcFieldType::UInt32 },
    { "EffectItemType2",            DbcFieldType::UInt32 },
    { "EffectItemType3",            DbcFieldType::UInt32 },
    { "EffectMiscValue1",           DbcFieldType::Int32  },
    { "EffectMiscValue2",           DbcFieldType::Int32  },
    { "EffectMiscValue3",           DbcFieldType::Int32  },
    { "EffectMiscValueB1",          DbcFieldType::Int32  },
    { "EffectMiscValueB2",          DbcFieldType::Int32  },
    { "EffectMiscValueB3",          DbcFieldType::Int32  },
    { "EffectTriggerSpell1",        DbcFieldType::UInt32 },
    { "EffectTriggerSpell2",        DbcFieldType::UInt32 },
    { "EffectTriggerSpell3",        DbcFieldType::UInt32 },
    { "EffectPointsPerComboPoint1", DbcFieldType::Float  },
    { "EffectPointsPerComboPoint2", DbcFieldType::Float  },
    { "EffectPointsPerComboPoint3", DbcFieldType::Float  },
    { "EffectSpellClassMaskA1",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskA2",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskA3",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskB1",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskB2",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskB3",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskC1",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskC2",     DbcFieldType::UInt32 },
    { "EffectSpellClassMaskC3",     DbcFieldType::UInt32 },
    { "SpellVisual1",               DbcFieldType::UInt32 },
    { "SpellVisual2",               DbcFieldType::UInt32 },
    { "SpellIconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spellicon" },
    { "ActiveIconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "activeicon" },
    { "SpellPriority",              DbcFieldType::UInt32 },
    { "SpellName_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellName_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName" },
    { "SpellNameFlag",              DbcFieldType::UInt32 },
    { "Rank_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "Rank_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank" },
    { "RankFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Description_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "DescriptionFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ToolTip_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTip_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip" },
    { "ToolTipFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ManaCostPercentage",         DbcFieldType::UInt32 },
    { "StartRecoveryCategory",      DbcFieldType::UInt32 },
    { "StartRecoveryTime",          DbcFieldType::UInt32 },
    { "MaxTargetLevel",             DbcFieldType::UInt32 },
    { "SpellFamilyName",            DbcFieldType::UInt32 },
    { "SpellFamilyFlags1",          DbcFieldType::UInt32 },
    { "SpellFamilyFlags2",          DbcFieldType::UInt32 },
    { "SpellFamilyFlags3",          DbcFieldType::UInt32 },
    { "MaxAffectedTargets",         DbcFieldType::UInt32 },
    { "DmgClass",                   DbcFieldType::UInt32 },
    { "PreventionType",             DbcFieldType::UInt32 },
    { "StanceBarOrder",             DbcFieldType::Int32  },
    { "DmgMultiplier1",             DbcFieldType::Float  },
    { "DmgMultiplier2",             DbcFieldType::Float  },
    { "DmgMultiplier3",             DbcFieldType::Float  },
    { "MinFactionId",               DbcFieldType::UInt32 },
    { "MinReputation",              DbcFieldType::UInt32 },
    { "RequiredAuraVision",         DbcFieldType::UInt32 },
    { "TotemCategory1",             DbcFieldType::UInt32 },
    { "TotemCategory2",             DbcFieldType::UInt32 },
    { "AreaGroupId",                DbcFieldType::Int32  },
    { "SchoolMask", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellSchoolMask" },
    { "RuneCostID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "runecost" },
    { "SpellMissileID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spellmissile" },
    { "PowerDisplayId",             DbcFieldType::Int32  },
    { "EffectBonusMultiplier1",     DbcFieldType::Float  },
    { "EffectBonusMultiplier2",     DbcFieldType::Float  },
    { "EffectBonusMultiplier3",     DbcFieldType::Float  },
    { "SpellDescriptionVariableID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spelldescriptionvariable" },
    { "SpellDifficultyId",          DbcFieldType::UInt32 },
};

static const DbcSchema schema_spell = {
    "Spell",
    spell_fields,
    sizeof(spell_fields) / sizeof(spell_fields[0])
};

#endif // SCHEMA_SPELL_H
