#ifndef SCHEMA_CHR_RACES_H
#define SCHEMA_CHR_RACES_H

#include "dbc_schema.h"

static const DbcFieldDef chr_races_fields[] = {
    { "Id", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Identity" },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "CharacterFlags", "Classification" },
    { "FactionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "faction" },
    { "ExplorationSoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "explorationsound", "Visuals" },
    { "MaleDisplayID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "creaturedisplayinfo", "Visuals" },
    { "FemaleDisplayID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "creaturedisplayinfo", "Visuals" },
    { "ClientPrefix", DbcFieldType::String },
    { "BaseLanguage", DbcFieldType::UInt32 },
    { "CreatureType", DbcFieldType::UInt32, DbcSemantic::Enum, "CreatureType" },
    { "ResSicknessSpellID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "ressicknessspell" },
    { "SplashSoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "splashsound", "Visuals" },
    { "ClientFileString", DbcFieldType::String },
    { "CinematicSequenceID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "cinematicsequence" },
    { "Alliance", DbcFieldType::UInt32 },
    { "Name_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "Name_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Name", "Identity" },
    { "NameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "NameFemale_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemale_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale", "Identity" },
    { "NameFemaleFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "NameMale_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMale_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale", "Identity" },
    { "NameMaleFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "FacialHairCustomization1", DbcFieldType::String },
    { "FacialHairCustomization2", DbcFieldType::String },
    { "HairCustomization", DbcFieldType::String },
    { "RequiredExpansion", DbcFieldType::UInt32 },
};

static const DbcSchema schema_chr_races = {
    "ChrRaces",
    chr_races_fields,
    sizeof(chr_races_fields) / sizeof(chr_races_fields[0])
};

#endif
