#ifndef SCHEMA_CHAR_START_OUTFIT_H
#define SCHEMA_CHAR_START_OUTFIT_H

#include "dbc_schema.h"

// Record size: 296 bytes
// Layout: uint32 Id, uint8 race/class/sex/outfit, then 24 items × 3 arrays
static const DbcFieldDef char_start_outfit_fields[] = {
    { "Id",               DbcFieldType::UInt32 },
    { "RaceID", DbcFieldType::UInt8, DbcSemantic::ForeignKey, "chrraces" },
    { "ClassID", DbcFieldType::UInt8, DbcSemantic::ForeignKey, "chrclasses" },
    { "SexID", DbcFieldType::UInt8, DbcSemantic::Enum, "Sex" },
    { "OutfitID", DbcFieldType::UInt8, DbcSemantic::ForeignKey, "outfit" },
    { "ItemID1",          DbcFieldType::Int32  },
    { "ItemID2",          DbcFieldType::Int32  },
    { "ItemID3",          DbcFieldType::Int32  },
    { "ItemID4",          DbcFieldType::Int32  },
    { "ItemID5",          DbcFieldType::Int32  },
    { "ItemID6",          DbcFieldType::Int32  },
    { "ItemID7",          DbcFieldType::Int32  },
    { "ItemID8",          DbcFieldType::Int32  },
    { "ItemID9",          DbcFieldType::Int32  },
    { "ItemID10",         DbcFieldType::Int32  },
    { "ItemID11",         DbcFieldType::Int32  },
    { "ItemID12",         DbcFieldType::Int32  },
    { "ItemID13",         DbcFieldType::Int32  },
    { "ItemID14",         DbcFieldType::Int32  },
    { "ItemID15",         DbcFieldType::Int32  },
    { "ItemID16",         DbcFieldType::Int32  },
    { "ItemID17",         DbcFieldType::Int32  },
    { "ItemID18",         DbcFieldType::Int32  },
    { "ItemID19",         DbcFieldType::Int32  },
    { "ItemID20",         DbcFieldType::Int32  },
    { "ItemID21",         DbcFieldType::Int32  },
    { "ItemID22",         DbcFieldType::Int32  },
    { "ItemID23",         DbcFieldType::Int32  },
    { "ItemID24",         DbcFieldType::Int32  },
    { "DisplayItemID1",   DbcFieldType::Int32  },
    { "DisplayItemID2",   DbcFieldType::Int32  },
    { "DisplayItemID3",   DbcFieldType::Int32  },
    { "DisplayItemID4",   DbcFieldType::Int32  },
    { "DisplayItemID5",   DbcFieldType::Int32  },
    { "DisplayItemID6",   DbcFieldType::Int32  },
    { "DisplayItemID7",   DbcFieldType::Int32  },
    { "DisplayItemID8",   DbcFieldType::Int32  },
    { "DisplayItemID9",   DbcFieldType::Int32  },
    { "DisplayItemID10",  DbcFieldType::Int32  },
    { "DisplayItemID11",  DbcFieldType::Int32  },
    { "DisplayItemID12",  DbcFieldType::Int32  },
    { "DisplayItemID13",  DbcFieldType::Int32  },
    { "DisplayItemID14",  DbcFieldType::Int32  },
    { "DisplayItemID15",  DbcFieldType::Int32  },
    { "DisplayItemID16",  DbcFieldType::Int32  },
    { "DisplayItemID17",  DbcFieldType::Int32  },
    { "DisplayItemID18",  DbcFieldType::Int32  },
    { "DisplayItemID19",  DbcFieldType::Int32  },
    { "DisplayItemID20",  DbcFieldType::Int32  },
    { "DisplayItemID21",  DbcFieldType::Int32  },
    { "DisplayItemID22",  DbcFieldType::Int32  },
    { "DisplayItemID23",  DbcFieldType::Int32  },
    { "DisplayItemID24",  DbcFieldType::Int32  },
    { "InventoryType1",   DbcFieldType::Int32  },
    { "InventoryType2",   DbcFieldType::Int32  },
    { "InventoryType3",   DbcFieldType::Int32  },
    { "InventoryType4",   DbcFieldType::Int32  },
    { "InventoryType5",   DbcFieldType::Int32  },
    { "InventoryType6",   DbcFieldType::Int32  },
    { "InventoryType7",   DbcFieldType::Int32  },
    { "InventoryType8",   DbcFieldType::Int32  },
    { "InventoryType9",   DbcFieldType::Int32  },
    { "InventoryType10",  DbcFieldType::Int32  },
    { "InventoryType11",  DbcFieldType::Int32  },
    { "InventoryType12",  DbcFieldType::Int32  },
    { "InventoryType13",  DbcFieldType::Int32  },
    { "InventoryType14",  DbcFieldType::Int32  },
    { "InventoryType15",  DbcFieldType::Int32  },
    { "InventoryType16",  DbcFieldType::Int32  },
    { "InventoryType17",  DbcFieldType::Int32  },
    { "InventoryType18",  DbcFieldType::Int32  },
    { "InventoryType19",  DbcFieldType::Int32  },
    { "InventoryType20",  DbcFieldType::Int32  },
    { "InventoryType21",  DbcFieldType::Int32  },
    { "InventoryType22",  DbcFieldType::Int32  },
    { "InventoryType23",  DbcFieldType::Int32  },
    { "InventoryType24",  DbcFieldType::Int32  },
};

static const DbcSchema schema_char_start_outfit = {
    "CharStartOutfit",
    char_start_outfit_fields,
    sizeof(char_start_outfit_fields) / sizeof(char_start_outfit_fields[0]),
    true
};

#endif
