#ifndef SCHEMA_VEHICLE_SEAT_H
#define SCHEMA_VEHICLE_SEAT_H

#include "dbc_schema.h"

static const DbcFieldDef vehicle_seat_fields[] = {
    { "Id", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Identity" },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "VehicleSeatFlags", "Classification" },
    { "AttachmentID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "attachment" },
    { "AttachmentOffsetX", DbcFieldType::Float },
    { "AttachmentOffsetY", DbcFieldType::Float },
    { "AttachmentOffsetZ", DbcFieldType::Float },
    { "EnterPreDelay", DbcFieldType::Float },
    { "EnterSpeed", DbcFieldType::Float },
    { "EnterGravity", DbcFieldType::Float },
    { "EnterMinDuration", DbcFieldType::Float },
    { "EnterMaxDuration", DbcFieldType::Float },
    { "EnterMinArcHeight", DbcFieldType::Float },
    { "EnterMaxArcHeight", DbcFieldType::Float },
    { "EnterAnimStart", DbcFieldType::Int32 },
    { "EnterAnimLoop", DbcFieldType::Int32 },
    { "RideAnimStart", DbcFieldType::Int32 },
    { "RideAnimLoop", DbcFieldType::Int32 },
    { "RideUpperAnimStart", DbcFieldType::Int32 },
    { "RideUpperAnimLoop", DbcFieldType::Int32 },
    { "ExitPreDelay", DbcFieldType::Float },
    { "ExitSpeed", DbcFieldType::Float },
    { "ExitGravity", DbcFieldType::Float },
    { "ExitMinDuration", DbcFieldType::Float },
    { "ExitMaxDuration", DbcFieldType::Float },
    { "ExitMinArcHeight", DbcFieldType::Float },
    { "ExitMaxArcHeight", DbcFieldType::Float },
    { "ExitAnimStart", DbcFieldType::Int32 },
    { "ExitAnimLoop", DbcFieldType::Int32 },
    { "ExitAnimEnd", DbcFieldType::Int32 },
    { "PassengerYaw", DbcFieldType::Float },
    { "PassengerPitch", DbcFieldType::Float },
    { "PassengerRoll", DbcFieldType::Float },
    { "PassengerAttachmentID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "passengerattachment" },
    { "VehicleEnterAnim", DbcFieldType::Int32 },
    { "VehicleExitAnim", DbcFieldType::Int32 },
    { "VehicleRideAnimLoop", DbcFieldType::Int32 },
    { "VehicleEnterAnimBone", DbcFieldType::Int32 },
    { "VehicleExitAnimBone", DbcFieldType::Int32 },
    { "VehicleRideAnimLoopBone", DbcFieldType::Int32 },
    { "VehicleEnterAnimDelay", DbcFieldType::Float },
    { "VehicleExitAnimDelay", DbcFieldType::Float },
    { "VehicleAbilityDisplay", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Visuals" },
    { "EnterUISoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "enteruisound", "Visuals" },
    { "ExitUISoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "exituisound", "Visuals" },
    { "UiSkin", DbcFieldType::UInt32 },
    { "FlagsB", DbcFieldType::UInt32, DbcSemantic::Bitmask, "VehicleSeatFlagsB" },
    { "CameraEnteringDelay", DbcFieldType::Float },
    { "CameraEnteringDuration", DbcFieldType::Float },
    { "CameraExitingDelay", DbcFieldType::Float },
    { "CameraExitingDuration", DbcFieldType::Float },
    { "CameraOffsetX", DbcFieldType::Float },
    { "CameraOffsetY", DbcFieldType::Float },
    { "CameraOffsetZ", DbcFieldType::Float },
    { "CameraPosChaseRate", DbcFieldType::Float },
    { "CameraFacingChaseRate", DbcFieldType::Float },
    { "CameraEnteringZoom", DbcFieldType::Float },
    { "CameraSeatZoomMin", DbcFieldType::Float },
    { "CameraSeatZoomMax", DbcFieldType::Float },
};

static const DbcSchema schema_vehicle_seat = {
    "VehicleSeat",
    vehicle_seat_fields,
    sizeof(vehicle_seat_fields) / sizeof(vehicle_seat_fields[0])
};

#endif
