#ifndef SCHEMA_SKILL_LINE_H
#define SCHEMA_SKILL_LINE_H

#include "dbc_schema.h"

static const DbcFieldDef skill_line_fields[] = {
    { "Id",              DbcFieldType::UInt32 },
    { "CategoryID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "category" },
    { "SkillCostID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "skillcost" },
    { "DisplayName_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayName_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "DisplayName" },
    { "DisplayNameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Description_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "DescriptionFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "SpellIconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spellicon" },
    { "AlternateVerb_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerb_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "AlternateVerb" },
    { "AlternateVerbFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "CanLink",         DbcFieldType::UInt32 },
};

static const DbcSchema schema_skill_line = {
    "SkillLine",
    skill_line_fields,
    sizeof(skill_line_fields) / sizeof(skill_line_fields[0])
};

#endif
