#ifndef SCHEMA_FACTION_H
#define SCHEMA_FACTION_H

#include "dbc_schema.h"

static const DbcFieldDef faction_fields[] = {
    { "Id",                  DbcFieldType::UInt32 },
    { "ReputationIndex",     DbcFieldType::Int32  },
    { "ReputationRaceMask1", DbcFieldType::UInt32 },
    { "ReputationRaceMask2", DbcFieldType::UInt32 },
    { "ReputationRaceMask3", DbcFieldType::UInt32 },
    { "ReputationRaceMask4", DbcFieldType::UInt32 },
    { "ReputationClassMask1", DbcFieldType::UInt32 },
    { "ReputationClassMask2", DbcFieldType::UInt32 },
    { "ReputationClassMask3", DbcFieldType::UInt32 },
    { "ReputationClassMask4", DbcFieldType::UInt32 },
    { "ReputationBase1",     DbcFieldType::Int32  },
    { "ReputationBase2",     DbcFieldType::Int32  },
    { "ReputationBase3",     DbcFieldType::Int32  },
    { "ReputationBase4",     DbcFieldType::Int32  },
    { "ReputationFlags1",    DbcFieldType::UInt32 },
    { "ReputationFlags2",    DbcFieldType::UInt32 },
    { "ReputationFlags3",    DbcFieldType::UInt32 },
    { "ReputationFlags4",    DbcFieldType::UInt32 },
    { "ParentFactionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "parentfaction" },
    { "ParentFactionMod1",   DbcFieldType::Float  },
    { "ParentFactionMod2",   DbcFieldType::Float  },
    { "ParentFactionCap1",   DbcFieldType::UInt32 },
    { "ParentFactionCap2",   DbcFieldType::UInt32 },
    { "Name_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "NameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Description_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "DescriptionFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
};

static const DbcSchema schema_faction = {
    "Faction",
    faction_fields,
    sizeof(faction_fields) / sizeof(faction_fields[0])
};

#endif
