#ifndef SCHEMA_HOLIDAYS_H
#define SCHEMA_HOLIDAYS_H

#include "dbc_schema.h"

static const DbcFieldDef holidays_fields[] = {
    { "Id",              DbcFieldType::UInt32 },
    { "Duration1",       DbcFieldType::UInt32 },
    { "Duration2",       DbcFieldType::UInt32 },
    { "Duration3",       DbcFieldType::UInt32 },
    { "Duration4",       DbcFieldType::UInt32 },
    { "Duration5",       DbcFieldType::UInt32 },
    { "Duration6",       DbcFieldType::UInt32 },
    { "Duration7",       DbcFieldType::UInt32 },
    { "Duration8",       DbcFieldType::UInt32 },
    { "Duration9",       DbcFieldType::UInt32 },
    { "Duration10",      DbcFieldType::UInt32 },
    { "Date1",           DbcFieldType::UInt32 },
    { "Date2",           DbcFieldType::UInt32 },
    { "Date3",           DbcFieldType::UInt32 },
    { "Date4",           DbcFieldType::UInt32 },
    { "Date5",           DbcFieldType::UInt32 },
    { "Date6",           DbcFieldType::UInt32 },
    { "Date7",           DbcFieldType::UInt32 },
    { "Date8",           DbcFieldType::UInt32 },
    { "Date9",           DbcFieldType::UInt32 },
    { "Date10",          DbcFieldType::UInt32 },
    { "Date11",          DbcFieldType::UInt32 },
    { "Date12",          DbcFieldType::UInt32 },
    { "Date13",          DbcFieldType::UInt32 },
    { "Date14",          DbcFieldType::UInt32 },
    { "Date15",          DbcFieldType::UInt32 },
    { "Date16",          DbcFieldType::UInt32 },
    { "Date17",          DbcFieldType::UInt32 },
    { "Date18",          DbcFieldType::UInt32 },
    { "Date19",          DbcFieldType::UInt32 },
    { "Date20",          DbcFieldType::UInt32 },
    { "Date21",          DbcFieldType::UInt32 },
    { "Date22",          DbcFieldType::UInt32 },
    { "Date23",          DbcFieldType::UInt32 },
    { "Date24",          DbcFieldType::UInt32 },
    { "Date25",          DbcFieldType::UInt32 },
    { "Date26",          DbcFieldType::UInt32 },
    { "Region",          DbcFieldType::UInt32 },
    { "Looping",         DbcFieldType::UInt32 },
    { "CalendarFlags1",  DbcFieldType::UInt32 },
    { "CalendarFlags2",  DbcFieldType::UInt32 },
    { "CalendarFlags3",  DbcFieldType::UInt32 },
    { "CalendarFlags4",  DbcFieldType::UInt32 },
    { "CalendarFlags5",  DbcFieldType::UInt32 },
    { "CalendarFlags6",  DbcFieldType::UInt32 },
    { "CalendarFlags7",  DbcFieldType::UInt32 },
    { "CalendarFlags8",  DbcFieldType::UInt32 },
    { "CalendarFlags9",  DbcFieldType::UInt32 },
    { "CalendarFlags10", DbcFieldType::UInt32 },
    { "HolidayNameID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "holidayname" },
    { "HolidayDescriptionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "holidaydescription" },
    { "TextureFilename", DbcFieldType::String },
    { "Priority",        DbcFieldType::UInt32 },
    { "CalendarFilterType", DbcFieldType::UInt32 },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
};

static const DbcSchema schema_holidays = {
    "Holidays",
    holidays_fields,
    sizeof(holidays_fields) / sizeof(holidays_fields[0])
};

#endif
