#ifndef SCHEMA_WORLD_STATE_UI_H
#define SCHEMA_WORLD_STATE_UI_H

#include "dbc_schema.h"

static const DbcFieldDef world_state_ui_fields[] = {
    { "Id",                    DbcFieldType::UInt32 },
    { "MapID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "map" },
    { "AreaID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "areatable" },
    { "PhaseShift",            DbcFieldType::UInt32 },
    { "Icon",                  DbcFieldType::String },
    { "String_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "String_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "String" },
    { "StringFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Tooltip_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "Tooltip_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Tooltip" },
    { "TooltipFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "DynamicIcon",           DbcFieldType::String },
    { "DynamicTooltip_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltip_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "DynamicTooltip" },
    { "DynamicTooltipFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "ExtendedUI",            DbcFieldType::String },
    { "ExtendedUIStateVar1",   DbcFieldType::UInt32 },
    { "ExtendedUIStateVar2",   DbcFieldType::UInt32 },
    { "ExtendedUIStateVar3",   DbcFieldType::UInt32 },
    { "Type",                  DbcFieldType::UInt32 },
    { "OrderIndex",            DbcFieldType::UInt32 },
};

static const DbcSchema schema_world_state_ui = {
    "WorldStateUI",
    world_state_ui_fields,
    sizeof(world_state_ui_fields) / sizeof(world_state_ui_fields[0])
};

#endif
