#ifndef SCHEMA_ACHIEVEMENT_H
#define SCHEMA_ACHIEVEMENT_H

#include "dbc_schema.h"

static const DbcFieldDef achievement_fields[] = {
    { "Id",                  DbcFieldType::UInt32 },
    { "Faction",             DbcFieldType::Int32  },
    { "MapID", DbcFieldType::Int32, DbcSemantic::ForeignKey, "map" },
    { "PreviousAchievement", DbcFieldType::UInt32 },
    { "Name_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "NameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Description_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "Description_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Description" },
    { "DescriptionFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "Category",            DbcFieldType::UInt32 },
    { "Points",              DbcFieldType::UInt32 },
    { "SortOrder",           DbcFieldType::UInt32 },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "AchievementFlags" },
    { "IconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "icon" },
    { "Reward_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "Reward_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Reward" },
    { "RewardFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "MinimumCriteria",     DbcFieldType::UInt32 },
    { "SharesCriteria",      DbcFieldType::UInt32 },
};

static const DbcSchema schema_achievement = {
    "Achievement",
    achievement_fields,
    sizeof(achievement_fields) / sizeof(achievement_fields[0])
};

#endif
