#ifndef SCHEMA_SPELL_H
#define SCHEMA_SPELL_H

#include "dbc_schema.h"

static const DbcFieldDef spell_fields[] = {
    { "Id", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Identity" },
    { "Category", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "Dispel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "Mechanic", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "Attributes", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr0", "Attributes" },
    { "AttributesEx", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr1", "Attributes" },
    { "AttributesEx2", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr2", "Attributes" },
    { "AttributesEx3", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr3", "Attributes" },
    { "AttributesEx4", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr4", "Attributes" },
    { "AttributesEx5", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr5", "Attributes" },
    { "AttributesEx6", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr6", "Attributes" },
    { "AttributesEx7", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellAttr7", "Attributes" },
    { "Stances", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions" },
    { "StancesHigh", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions" },
    { "StancesNot", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions" },
    { "StancesNotHigh", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions" },
    { "Targets", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Targeting" },
    { "TargetCreatureType", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Targeting" },
    { "RequiresSpellFocus", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Targeting" },
    { "FacingCasterFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Targeting" },
    { "CasterAuraState", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "TargetAuraState", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "CasterAuraStateNot", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "TargetAuraStateNot", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "CasterAuraSpell", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "TargetAuraSpell", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "ExcludeCasterAuraSpell", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "ExcludeTargetAuraSpell", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "CastingTimeIndex", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "RecoveryTime", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "CategoryRecoveryTime", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "InterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Proc" },
    { "AuraInterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Proc" },
    { "ChannelInterruptFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Proc" },
    { "ProcFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Proc" },
    { "ProcChance", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Proc" },
    { "ProcCharges", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Proc" },
    { "MaxLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "BaseLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "SpellLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "DurationIndex", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "PowerType", DbcFieldType::Int32, DbcSemantic::Enum, "PowerType", "Cast" },
    { "ManaCost", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "ManaCostPerLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "ManaPerSecond", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "ManaPerSecondPerLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "RangeIndex", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "Speed", DbcFieldType::Float },
    { "ModalNextSpell", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "StackAmount", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Proc" },
    { "Totem1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Totem2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent1", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent2", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent3", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent4", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent5", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent6", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent7", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "Reagent8", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount4", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount5", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount6", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount7", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "ReagentCount8", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "EquippedItemClass", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "EquippedItemSubClassMask", DbcFieldType::Int32, DbcSemantic::Bitmask, nullptr, "Conditions", true },
    { "EquippedItemInventoryTypeMask", DbcFieldType::Int32, DbcSemantic::Bitmask, nullptr, "Conditions", true },
    { "Effect1", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellEffects", "Effects" },
    { "Effect2", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellEffects", "Effects", true },
    { "Effect3", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellEffects", "Effects", true },
    { "EffectDieSides1", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectDieSides2", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectDieSides3", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectRealPointsPerLevel1", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectRealPointsPerLevel2", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectRealPointsPerLevel3", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectBasePoints1", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectBasePoints2", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectBasePoints3", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMechanic1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectMechanic2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMechanic3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectImplicitTargetA1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectImplicitTargetA2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectImplicitTargetA3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectImplicitTargetB1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectImplicitTargetB2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectImplicitTargetB3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectRadiusIndex1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectRadiusIndex2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectRadiusIndex3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectApplyAuraName1", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellAuraType", "Effects" },
    { "EffectApplyAuraName2", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellAuraType", "Effects", true },
    { "EffectApplyAuraName3", DbcFieldType::UInt32, DbcSemantic::Enum, "SpellAuraType", "Effects", true },
    { "EffectAmplitude1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectAmplitude2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectAmplitude3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMultipleValue1", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectMultipleValue2", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMultipleValue3", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectChainTarget1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectChainTarget2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectChainTarget3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectItemType1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectItemType2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectItemType3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMiscValue1", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectMiscValue2", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMiscValue3", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMiscValueB1", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectMiscValueB2", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectMiscValueB3", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectTriggerSpell1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectTriggerSpell2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectTriggerSpell3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectPointsPerComboPoint1", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectPointsPerComboPoint2", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectPointsPerComboPoint3", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskA1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectSpellClassMaskA2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskA3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskB1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectSpellClassMaskB2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskB3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskC1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectSpellClassMaskC2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectSpellClassMaskC3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Effects", true },
    { "SpellVisual1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Visuals" },
    { "SpellVisual2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Visuals" },
    { "SpellIconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spellicon", "Visuals" },
    { "ActiveIconID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "activeicon", "Identity" },
    { "SpellPriority", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "SpellName_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellName_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "SpellName", "Identity" },
    { "SpellNameFlag", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Identity" },
    { "Rank_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "Rank_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Rank", "Identity" },
    { "RankFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "Description_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "Description_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Description", "Identity" },
    { "DescriptionFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "ToolTip_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTip_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "ToolTip", "Identity" },
    { "ToolTipFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask, nullptr, "Identity" },
    { "ManaCostPercentage", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "StartRecoveryCategory", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "StartRecoveryTime", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Cast" },
    { "MaxTargetLevel", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Targeting" },
    { "SpellFamilyName", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "SpellFamilyFlags1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "SpellFamilyFlags2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "SpellFamilyFlags3", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "MaxAffectedTargets", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Targeting" },
    { "DmgClass", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Classification" },
    { "PreventionType", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Proc" },
    { "StanceBarOrder", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Advanced", true },
    { "DmgMultiplier1", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects" },
    { "DmgMultiplier2", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "DmgMultiplier3", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "MinFactionId", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "MinReputation", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "RequiredAuraVision", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "TotemCategory1", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "TotemCategory2", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Reagents" },
    { "AreaGroupId", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Conditions", true },
    { "SchoolMask", DbcFieldType::UInt32, DbcSemantic::Bitmask, "SpellSchoolMask", "Classification" },
    { "RuneCostID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "runecost", "Cast" },
    { "SpellMissileID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spellmissile", "Visuals" },
    { "PowerDisplayId", DbcFieldType::Int32, DbcSemantic::Default, nullptr, "Cast" },
    { "EffectBonusMultiplier1", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects" },
    { "EffectBonusMultiplier2", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "EffectBonusMultiplier3", DbcFieldType::Float, DbcSemantic::Default, nullptr, "Effects", true },
    { "SpellDescriptionVariableID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "spelldescriptionvariable", "Advanced", true },
    { "SpellDifficultyId", DbcFieldType::UInt32, DbcSemantic::Default, nullptr, "Advanced", true },
};

static const DbcSchema schema_spell = {
    "Spell",
    spell_fields,
    sizeof(spell_fields) / sizeof(spell_fields[0])
};

#endif // SCHEMA_SPELL_H
