#ifndef SCHEMA_CHR_RACES_H
#define SCHEMA_CHR_RACES_H

#include "dbc_schema.h"

static const DbcFieldDef chr_races_fields[] = {
    { "Id",                     DbcFieldType::UInt32 },
    { "Flags", DbcFieldType::UInt32, DbcSemantic::Bitmask, "CharacterFlags" },
    { "FactionID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "faction" },
    { "ExplorationSoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "explorationsound" },
    { "MaleDisplayID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "creaturedisplayinfo" },
    { "FemaleDisplayID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "creaturedisplayinfo" },
    { "ClientPrefix",           DbcFieldType::String },
    { "BaseLanguage",           DbcFieldType::UInt32 },
    { "CreatureType", DbcFieldType::UInt32, DbcSemantic::Enum, "CreatureType" },
    { "ResSicknessSpellID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "ressicknessspell" },
    { "SplashSoundID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "splashsound" },
    { "ClientFileString",       DbcFieldType::String },
    { "CinematicSequenceID", DbcFieldType::UInt32, DbcSemantic::ForeignKey, "cinematicsequence" },
    { "Alliance",               DbcFieldType::UInt32 },
    { "Name_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "Name_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "Name" },
    { "NameFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "NameFemale_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemale_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "NameFemale" },
    { "NameFemaleFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "NameMale_enUS", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_koKR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_frFR", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_deDE", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_enCN", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_zhTW", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_esES", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_esMX", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_ruRU", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_jaJP", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_ptPT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_itIT", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_Unk1", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_Unk2", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_Unk3", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMale_Unk4", DbcFieldType::String, DbcSemantic::LocalizedString, "NameMale" },
    { "NameMaleFlags", DbcFieldType::UInt32, DbcSemantic::Bitmask },
    { "FacialHairCustomization1", DbcFieldType::String },
    { "FacialHairCustomization2", DbcFieldType::String },
    { "HairCustomization",      DbcFieldType::String },
    { "RequiredExpansion",      DbcFieldType::UInt32 },
};

static const DbcSchema schema_chr_races = {
    "ChrRaces",
    chr_races_fields,
    sizeof(chr_races_fields) / sizeof(chr_races_fields[0])
};

#endif
